name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (unit)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest tests/test_options.py tests/test_show.py

  renderers:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (renderers)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install tensorflow aggdraw

      - name: Regenerate renderer baselines (optional)
        run: python tests/renderer_baselines/generate_renderer_references.py

      - name: Run renderer tests
        run: pytest tests/test_layered_renderer.py tests/test_graph_renderer.py
